import csv
import argparse
import os
import re

def load_base_units(kb_dir):
    units = set()
    csv_path = os.path.join(kb_dir, "base_unit.csv")
    if os.path.exists(csv_path):
        with open(csv_path, 'r', encoding='utf-8') as f:
             reader = csv.DictReader(f)
             for row in reader:
                 units.add(row['unit'])
    return units

def validate_markdown(input_file, base_units):
    if not os.path.exists(input_file):
        print(f"Erro: Arquivo {input_file} não encontrado.")
        return

    with open(input_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        
    validation_passed = True
    print(f"Validando {input_file}...")
    
    # Regex to find table row: | ID | Desc | Qtd | Unit |
    # Assuming standard format generated by cria_orcamento
    table_regex = re.compile(r"\|\s*`?([^`|]+)`?\s*\|\s*([^|]+)\s*\|\s*([\d\.]+)\s*\|\s*([^|]+)\s*\|")
    
    for i, line in enumerate(lines):
        match = table_regex.search(line)
        if match:
            svc_id = match.group(1).strip()
            desc = match.group(2).strip()
            qtd = match.group(3).strip()
            unit = match.group(4).strip()
            
            # Header check (skip header line if matched)
            if "ID" in svc_id or "---" in line:
                continue
                
            if unit not in base_units:
                print(f"[LINHA {i+1}] AVISO: Unidade '{unit}' não encontrada na base de conhecimento. Unidades válidas: {base_units}")
                # We won't block execution for now, just warn.
                # validation_passed = False 

    if validation_passed:
        print("Validação concluída. Nenhum erro bloqueante encontrado.")
    else:
        print("Validação concluída com avisos.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Validar orçamento MD")
    parser.add_argument("--input", required=True, help="Arquivo MD de entrada")
    parser.add_argument("--kb_dir", required=True, help="Diretório da Knowledge Base")
    
    args = parser.parse_args()
    
    units = load_base_units(args.kb_dir)
    validate_markdown(args.input, units)
